doctorapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),    
    path('doctorshots/', include('doctorshots.urls'))
]

doctorshots/urls.py
from django.urls import path

from . import views
app_name = 'doctorshots'

urlpatterns = [
    path('', views.index, name='inicio'),
    path('formlogin/<str:mensaje>/', views.formularioLogin, name='formlogin'),
    path('login/', views.login, name='login'),
    path('logout',views.logout, name='logout'),
    path('formempleado/<str:mensaje>/', views.formularioEmpleado, name='formempleado'),
    path('guardarempleado', views.guardarEmpleado, name="guardarempleado"),
    path('eliminarempleado/<int:id>/', views.eliminarEmpleado, name='eliminarempleado'),
    path('editarempleado/<int:id>/', views.editarEmpleado, name='editarempleado' ),
    path('actualizarempleado',views.actualizarEmpleado, name='actualizarempleado'),
    path('carta', views.carta, name='carta' ),
    path('inventario/<str:mensaje>/', views.inventario, name='inventario'),
    path('guardarproducto', views.guardarproducto, name="guardarproducto"),
    path('eliminarproducto/<int:id>/', views.eliminarproducto, name='eliminarproducto'),






    
]

doctorshots/models.py
from django.db import models

# Create your models here.
class Usuarios(models.Model):
    cedula = models.CharField(max_length=20, unique=True)
    nombres= models.CharField(max_length=50, default='')
    usuario = models.CharField(max_length=45)
    clave = models.CharField(max_length=50)
    ROLES=(
        ('1','empleado'),
        ('2','administrador'),
        ('3','usuario')
    )
    Rol= models.CharField(max_length=1, choices=ROLES, default='1')
    
    #METODOS
    def __str__(self):
        return self.usuario

class Productos(models.Model):
    codigoProducto = models.CharField(max_length=15,  unique=True)
    nombreProducto = models.CharField(max_length=45 )
    precioVenta = models.FloatField()
    precioCompra = models.FloatField()
    habilitado = models.BooleanField(default=True)
    cantidad = models.IntegerField()

    #Metodos 
    def __str__(self):
        return self.nombreProducto
        
    
    

doctorshots/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.forms.models import model_to_dict

from doctorshots.models import Usuarios, Productos


def index(request):

        return render(request, 'doctorshots/index.html')


def login(request):
    try:
        user = request.POST['usuario']
        passw = request.POST['clave']
        # verificar si hay un registro con ese usuario y clave
        q = Usuarios.objects.get(usuario=user, clave=passw)
        # en caso afirmativo, creo la variable de sesión
        request.session['logueado'] = [
            q.cedula, q.usuario, q.clave, q.Rol, q.nombres]
        return render(request, 'doctorshots/index.html')
    except Exception as e:
        return HttpResponseRedirect(reverse('doctorshots:formlogin', args=(e,)))


def logout(request):
    del request.session['logueado']
    return render(request, 'doctorshots/index.html')


def formularioLogin(request, mensaje):
    contexto = {'mensaje': mensaje}

    return render(request, 'doctorshots/login.html', contexto)


def formularioEmpleado(request, mensaje):
            ses = request.session.get('logueado', False)
            if ses and (ses[3] == "2" or ses[3] == "1" ):
                
                q= Usuarios.objects.all()

                contexto = {'datos': q , 'mensaje': mensaje  }
                return render(request,'doctorshots/form-crear-empleado.html',contexto)
            else:
                return HttpResponse("Usted no tiene permiso para ver aprendices ")







def guardarEmpleado(request):
    ses = request.session.get('logueado', False)
    if ses and (ses[3] == "2" or ses[3] == "1" ):
        try:
            empleado = Usuarios(
                cedula = request.POST['cedula'],
                nombres= request.POST['nombres'],
                usuario = request.POST['usuario'],
                clave = request.POST['clave'],
                Rol = request.POST['Rol']
            )
            empleado.save()
            
            q = Usuarios.objects.all()
            contexto = {'datos': q}
            
            return HttpResponseRedirect(reverse ('doctorshots:formempleado' ,args=('GuardadoCorrectamente',))) 
        except Exception as e:
            return HttpResponseRedirect(reverse('doctorshots:formempleado',args=(e,)))
    else:
        return HttpResponse("Usted no tiene permiso para crear aprendices ")        

def eliminarEmpleado(request,id):
        ses = request.session.get('logueado', False)
        if ses and (ses[3] == "2" or ses[3] == "1" ):
            try:
                q = Usuarios.objects.get(pk=id)
                print(q)
                q.delete()
                return HttpResponseRedirect(reverse('doctorshots:formempleado', args=('Eliminado Correctamente',)))
            except Exception as e:
                return HttpResponseRedirect(reverse('doctorshots:formempleado', args=(e,)))
        else:
            return HttpResponse("Usted no tiene permiso para eliminar aprendices ")        

def editarEmpleado(request, id):
    ses = request.session.get('logueado', False)
    if ses and (ses[3] == "2" or ses[3] == "1" ):
            try:
                q= Usuarios.objects.get(pk=id)
                contexto = {'empleado':q}
                return render(request,'doctorshots/form-editar-empleado.html',contexto)
            except Exception as e:
                return HttpResponseRedirect(reverse('doctorshots:formempleado', args=(e,)))
    else:
            return HttpResponse("Usted no tiene permiso para editar aprendices ")        


def actualizarEmpleado(request):
        ses = request.session.get('logueado', False)
        if (ses[3] == "2" or ses[3] == "1" ):
            try:
                id= request.POST['id']
                q = Usuarios.objects.get(pk=id)
                q.cedula= request.POST['cedula']
                q.nombres= request.POST['nombres']
                q.usuario= request.POST['usuario']
                q.clave= request.POST['clave']
                q.Rol= request.POST['Rol']
                q.save()
                return HttpResponseRedirect(reverse('doctorshots:formempleado' ,args=('actualizado correctamente',)))
            except Exception as e:
                return HttpResponse(e)
        else:
            return HttpResponse("Usted no tiene permiso para editar aprendices ")    

def carta(request):
    return render(request, 'doctorshots/carta.html')  



    # inventario

    
def inventario(request ,mensaje):
    q = Productos.objects.all()
    contexto = {'datos': q, 'mensaje': mensaje }
    return render(request,'doctorshots/form-crear-producto.html',contexto)

def guardarproducto(request):
    try:
        producto = Productos(
            codigoProducto = request.POST['codigoProducto'],
            nombreProducto= request.POST['nombreProducto'],
            precioVenta = request.POST['precioVenta'],
            precioCompra = request.POST['precioCompra'],
            habilitado = request.POST['habilitado'],
            cantidad = request.POST['cantidad']
        )
        producto.save()
        
        q = Productos.objects.all()
        contexto = {'datos': q}
        
        return HttpResponseRedirect(reverse ('doctorshots:inventario' ,args=('GuardadoCorrectamente',))) 
    except Exception as e:
        return HttpResponse(e)

def eliminarproducto(request,id):
    try:
        q = Productos.objects.get(pk=id)
        print(q)
        q.delete()
        return HttpResponseRedirect(reverse('doctorshots:inventario', args=('Eliminado Correctamente',)))
    except Exception as e:
        return HttpResponseRedirect(reverse('doctorshots:inventario', args=(e,)))
    
def editarEmpleado(request, id):
    try:
        q= Usuarios.objects.get(pk=id)
        contexto = {'empleado':q}
        return render(request,'doctorshots/form-editar-empleado.html',contexto)
    except Exception as e:
        return HttpResponseRedirect(reverse('doctorshots:formempleado', args=(e,)))

def actualizarEmpleado(request):
    try:
        id= request.POST['id']
        q = Usuarios.objects.get(pk=id)
        q.cedula= request.POST['cedula']
        q.nombres= request.POST['nombres']
        q.usuario= request.POST['usuario']
        q.clave= request.POST['clave']
        q.Rol= request.POST['Rol']
        q.save()
        return HttpResponseRedirect(reverse('doctorshots:formempleado' ,args=('actualizado correctamente',)))
    except Exception as e:
        return HttpResponse(e)

doctorshots/templates/doctorshots/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Expires" CONTENT="0">
    <meta http-equiv="Cache-Control" CONTENT="no-cache">
    <meta http-equiv="Pragma" CONTENT="no-cache">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"  href="{% static 'doctorshots/mycss/contenido.css' %}">
      <link rel="stylesheet"  href="{% static 'doctorshots/mycss/modoResponsive.css' %}">      
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'doctorshots/mycss/miestilo.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
	<link rel="stylesheet" href="{% static 'doctorshots/mycss/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'doctorshots/mycss/animate.css' %}">
    

	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <title> {% block titulo %} {% endblock %}</title>
</head>
{% block body %} {% endblock %} {% block header %} {% endblock %} {% if request.session.logueado.3 != '1' and request.session.logueado.3 != '2' %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark " style="margin-bottom: 500px">
    <a class="navbar-brand" href="{% url 'doctorshots:inicio' %}">
        <img src="{% static 'doctorshots/img/logo.png' %}" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active" id="example">
                <a class="nav-link carta"   href="{% url 'doctorshots:carta' %}">Carta <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">Eventos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="">Mapa</a>
            </li>
            <li class=" nav-item buttonlogin">
                <a class="nav-link mr-sm-2"   href="{% url 'doctorshots:formlogin' 'false' %}"> Login</a>
            </li>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="">USER</a>
            </li>
        </ul>

    </div>
</nav>

{% elif request.session.logueado.3 == '2' %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark " style="margin-bottom: 500px">
    <a class="navbar-brand" href="{% url 'doctorshots:inicio' %}">
        <img src="{% static 'doctorshots/img/logo.png' %}" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'doctorshots:formempleado' 'False' %}"> Empleados <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link"  href="{% url 'doctorshots:carta' %}"> Carta <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'doctorshots:inventario' 'False' %}">Inventario</a>
            </li>
            <li class="nav-item" >
                <a class="nav-link "  href="#">Ventas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'doctorshots:logout' %}">Cerrar Sesion</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="">ADMIN</a>
            </li>


        </ul>

    </div>
</nav>

{% elif request.session.logueado.3 == '1' %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark " style="margin-bottom: 500px">
    <a class="navbar-brand" href="{% url 'doctorshots:inicio' %}">
        <img src="{% static 'doctorshots/img/logo.png' %}" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a id="carta"  class="nav-link" href="{% url 'doctorshots:carta' %}"> Carta <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Eventos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Mapa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'doctorshots:logout' %}">Cerrar Sesion</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="">EMPLEADO</a>
            </li>
        </ul>

    </div>
</nav>
{%endif%}
</header>

{% block contenedor %}
{% endblock %}

{% block parallax %}
{% endblock %}

<div id="complement">
    {% block complement %}
    {% endblock %}
</div>


        <!--Scripts-->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="{% static 'doctorshots/js/mijs.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="{% static 'doctorshots/js/parallax.min.js'%}"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="static/doctorshots/js/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="{% static 'doctorshots/js/modernizrmy.js' %}"></script>
        <script src="{% static 'doctorshots/js/mainmy.js' %}"></script>
        <script src="{% static 'doctorshots/js/bootstrapmy.min.js' %}"></script>
        <script>
            $(function () {
              $('#TabProducts a:first').tab('show')
            });
            $('#TabProducts a').click(function (e) {
                e.preventDefault()
                $(this).tab('show')
              });
          </script>
        </body>


</html>

doctorshots/templates/doctorshots/form-crear-empleado.html
{% extends 'doctorshots/base.html' %} {% load staticfiles%} {% block titulo %} Formulario-Empleados {% endblock %} {% block body %}

<body class="body-empleado sulley"> {% endblock %} {% block header %}
    <header class="header-empleado"> {% endblock %} {% block contenedor %}
        <div class="container-fluid">

            <div class="d-flex margin-top-my mt-4">
                <div class="card col-sm-6-my ">
                    <div class="card-body ">
                        <form action="{% url 'doctorshots:guardarempleado' %}" method="POST">
                            {% csrf_token %}

                            <div class="form-group">
                                <label class="campos">Cedula</label>
                                <input type="text" name="cedula" class="form-control">
                            </div>

                            <div class="form-group">
                                <label class="campos">Nombres</label>
                                <input type="text" name="nombres" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label class="campos">Usuario</label>
                                <input type="text" name="usuario" class="form-control" required>
                            </div>




                            <div class="form-group">
                                <label class="campos">Contraseña</label>
                                <input type="text" name="clave" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label class="campos">Rol</label><br>
                                <select name="Rol" class="browser-default custom-select">
                                <option selected>Elige</option>
                                <option class="font-drop upper font-color-drop-little" value="1">Empleado</option>
                                <option class="font-drop upper font-color-drop-little" value="2">Administrador</option>
                            </select>
                            </div>

                            <input type="submit" name="accion" value="Agregar" class="btn btn-info">
                        </form>
                    </div>
                         {% if '1062' in mensaje %}
                    <div class="alert alert-danger" role="alert">
                        Ya existe un empleado con esta cedula
                    </div>
                 {% elif '1265' in mensaje %}
                   <div class="alert alert-danger" role="alert">
                        Ingrese una cedula valida
                         
                    </div>   
                {% elif '1264' in mensaje %}
                     <div class="alert alert-danger" role="alert">
                        Ingrese una cedula valida
                    </div>
                {% elif '1366' in mensaje %}
                     <div class="alert alert-danger" role="alert">
                        Ingrese solo numeros en la cedula 
                    </div>   
                {% elif '1406' in mensaje %}
                     <div class="alert alert-danger" role="alert">
                        seleccione un rol
                    </div> 
                {% elif 'GuardadoCorrectamente' in mensaje %}
                    <div class="alert alert-success" role="alert">
                        Empleado Guardado con exito
                    </div>
                {% endif %}
                </div>

                <div class="col-sm-7 tamam">
                    <table class="table table-dark opacity">
                        <thead>
                            <tr>
                                <th class="font-drop upper font-color-drop">Cedula</th>
                                <th class="font-drop upper font-color-drop">Usuario</th>
                                <th class="font-drop upper font-color-drop">Rol</th>
                                <th class="font-drop upper font-color-drop">Acciones</th>

                            </tr>
                        </thead>
                        {% for empleado in datos %}
                        <tr>
                            <td class="font-Neon">{{empleado.cedula}} </td>
                            <td class="font-pacman">{{empleado.nombres}}</td>
                            {%if empleado.Rol == '2' %}
                            <td><img src=" {% static 'doctorshots/img/administrador.png' %}"></td>
                            {% elif empleado.Rol == '1' %}
                            <td><img src="{% static 'doctorshots/img/barman.png' %}"> </td>
                            {% endif %}
                            <td>
                                <a class="btn btn-warning font-drop" data-toggle="modal" data-target="#modalEmpleado" onclick="editarEmpleado('{% url 'doctorshots:editarempleado' empleado.id %} ') ">Editar</a>


                                <a class="btn btn-danger font-drop" href="{% url 'doctorshots:eliminarempleado' empleado.id %}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <!--Modal editar Empleado-->
                <div class="modal fade" id="modalEmpleado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Editar Empledo</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                            </div>
                            <div class="modal-body" id="modaleditar">

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
              



                {% endblock %}

doctorshots/templates/doctorshots/form-crear-producto.html
{% extends 'doctorshots/base.html' %} {% load staticfiles%} {% block titulo %} Formulario-productos{% endblock %} {% block body %}

<body class="body-inventario sulley"> {% endblock %} {% block header %}
    <header class="header-empleado"> {% endblock %} {% block contenedor %}
        <div class="container-fluid">

            <div class="d-flex margin-top-my mt-4">
                <div class="card col-sm-6-my ">
                    <div class="card-body ">
                        <form action="{% url 'doctorshots:guardarproducto' %}" method="POST">
                            {% csrf_token %}

                            <div class="form-group">
                                <label class="campos">Codigo de producto</label>
                                <input type="text" name="codigoProducto" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="campos">Nombre</label>
                                <input type="text" name="nombreProducto" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label class="campos">precio de venta</label>
                                <input type="number" name="precioVenta" class="form-control" required>
                            </div>




                            <div class="form-group">
                                <label class="campos">Costo</label>
                                <input type="text" name="precioCompra" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label class="campos">habilitado</label><br>
                                <select name="habilitado" class="browser-default custom-select">
                                <option selected>Elige</option>
                                <option class="font-drop upper font-color-drop-little" value="1">habilitado</option>
                                <option class="font-drop upper font-color-drop-little" value="2">deshabilitado</option>
                            </select>
                            </div>
                            <div class="form-group">
                                <label class="campos">Cantidad</label>
                                <input type="number" name="cantidad" class="form-control" required>
                            </div>
                            <input type="submit" name="accion" value="Agregar" class="btn btn-info">
                        </form>
                    </div>
                         {% if '1062' in mensaje %}
                    <div class="alert alert-danger" role="alert">
                        Ya existe un empleado con esta cedula
                    </div>
                 {% elif '1265' in mensaje %}
                   <div class="alert alert-danger" role="alert">
                    Ingrese un precio valido
                        
                         
                    </div>   
                {% elif '1264' in mensaje %}
                     <div class="alert alert-danger" role="alert">
                        Ingrese un precio valido
                    </div>
                {% elif '1366' in mensaje %}
                     <div class="alert alert-danger" role="alert">
                        Ingrese solo numeros en los precios
                    </div>   
                {% elif '1406' in mensaje %}
                     <div class="alert alert-danger" role="alert">
                        seleccione una habilitacion
                    </div> 
                {% elif 'GuardadoCorrectamente' in mensaje %}
                    <div class="alert alert-success" role="alert">
                        Producto Guardado con exito
                    </div>
                {% endif %}
                </div>

                <div class="col-sm-7 tamam">
                    <table class="table table-dark opacity">
                        <thead>
                            <tr>
                                <th class="font-drop upper font-color-drop">Id</th>
                                <th class="font-drop upper font-color-drop">Codigo</th>
                                <th class="font-drop upper font-color-drop">Nombre</th>
                                <th class="font-drop upper font-color-drop">Precio</th>
                                <th class="font-drop upper font-color-drop">Costo</th>
                                <th class="font-drop upper font-color-drop">Habilitado</th>
                                <th class="font-drop upper font-color-drop">Cantidad</th>
                                <th class="font-drop upper font-color-drop">Acciones</th>



                            </tr>
                        </thead>
                        {% for producto in datos %}
                        <tr>
                            <td class="font-Neon">{{producto.id}} </td>
                            <td class="font-pacman">{{producto.codigoProducto}}</td>
                            <td class="font-pacman">{{producto.nombreProducto}}</td>
                            <td class="font-pacman">{{producto.precioVenta}}</td>
                            <td class="font-pacman">{{producto.precioCompra}}</td>
                            <td class="font-pacman">{{producto.habilitado}}</td>
                            <td class="font-pacman">{{producto.cantidad}}</td>
                            <td>
                                <a class="btn btn-warning font-drop"  >Editar</a>
                            </td>

                            <td>

                                <a class="btn btn-danger font-drop" href="{% url 'doctorshots:eliminarproducto' producto.id %}">Delete</a>
                            </td>



                            
                        </tr>
                        {% endfor %}
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <!--Modal editar Empleado-->
                <div class="modal fade" id="modalEmpleado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Editar Empledo</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                            </div>
                            <div class="modal-body" id="modaleditar">

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>



                {% endblock %}

doctorshots/templates/doctorshots/form-editar-empleado.html
<form action="{% url 'doctorshots:actualizarempleado' %}" method="POST">
    {% csrf_token %}


    <div class="form-group">
        <input type="hidden" name="id" class="form-control" value="{{ empleado.id}}" readonly>
    </div>

    <div class="form-group">
        <input type="text" name="cedula" class="form-control" value="{{ empleado.cedula }}" readonly>
    </div>

      <div class="form-group">
        <input type="text" name="nombres" class="form-control" value="{{ empleado.nombres }}" readonly>
    </div>



    <div class="form-group">
        <input type="text" name="usuario" class="form-control" value="{{ empleado.usuario }}" >
    </div>


    <div class="form-group">
        <input type="text" name="clave" class="form-control" placeholder="clave">
    </div>

    <div class="form-group">
        <label class="font-drop upper font-color-drop-little">Rol</label><br>
        <select name="Rol" class="browser-default custom-select">
                                <option selected>Elige</option>
                                <option class="font-drop upper font-color-drop-little" value="2">Administrador</option>
                                <option class="font-drop upper font-color-drop-little" value="1">Empleado</option>
                            </select>
    </div>

    <input type="submit" name="accion" value="Editar" class="btn btn-info">
</form>